// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.tcg.followers",
    "name": "TCG Followers",
    "description": "This plugin adds functionality for push notifications when followed users post.",
    "homepage_url": "https://github.com/mattermost/mattermost-plugin-starter-template",
    "support_url": "https://github.com/mattermost/mattermost-plugin-starter-template/issues",
    "icon_path": "assets/starter-template-icon.svg",
    "version": "0.0.0+8d6dec2",
    "min_server_version": "6.2.1",
    "server": {
        "executables": {
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "darwin-arm64": "server/dist/plugin-darwin-arm64",
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "linux-arm64": "server/dist/plugin-linux-arm64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": []
    }
}
`);

export default manifest;
